spring:
  application:
    name: "console-task-app"

user: root
password: password

logging:
  pattern:
    console: "%msg%n"
#    console: "%d  %logge%-5levelr : %msg%n"
#    file: %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n