spring:
  application:
    name: task-4-elasticsearch-java-api-client

server:
  port: 8080

elastic-search:
  host: http://localhost:9200/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true