# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: ticket_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    expose: # allow access in docker network only (service not available from host)
      - 5432:5432
    ports: # allow access from host to services in docker (service available from host)
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ticket_booking
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - 27017:27017
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@ticket_booking:27017/
      ME_CONFIG_BASICAUTH: false